// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWMOpCKg--0AfYlGNlTT1BV8wT7HjbTOw',
    appId: '1:197487508921:web:84c1b4d0bc5e4dae0d8a68',
    messagingSenderId: '197487508921',
    projectId: 'intro-dev-mobile',
    authDomain: 'intro-dev-mobile.firebaseapp.com',
    storageBucket: 'intro-dev-mobile.firebasestorage.app',
    measurementId: 'G-KLZSV9FPQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNemWhQZKiFL5LzRlvVA-aztxEPTle0m8',
    appId: '1:197487508921:android:4624b9148dcff2e40d8a68',
    messagingSenderId: '197487508921',
    projectId: 'intro-dev-mobile',
    storageBucket: 'intro-dev-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqVJqJF8pQLdocI5diRcy4MJ4k19KMNxU',
    appId: '1:197487508921:ios:b33c9a61e78e6f900d8a68',
    messagingSenderId: '197487508921',
    projectId: 'intro-dev-mobile',
    storageBucket: 'intro-dev-mobile.firebasestorage.app',
    iosBundleId: 'com.example.degradedPointsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqVJqJF8pQLdocI5diRcy4MJ4k19KMNxU',
    appId: '1:197487508921:ios:b33c9a61e78e6f900d8a68',
    messagingSenderId: '197487508921',
    projectId: 'intro-dev-mobile',
    storageBucket: 'intro-dev-mobile.firebasestorage.app',
    iosBundleId: 'com.example.degradedPointsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWMOpCKg--0AfYlGNlTT1BV8wT7HjbTOw',
    appId: '1:197487508921:web:748ccb819d30a0060d8a68',
    messagingSenderId: '197487508921',
    projectId: 'intro-dev-mobile',
    authDomain: 'intro-dev-mobile.firebaseapp.com',
    storageBucket: 'intro-dev-mobile.firebasestorage.app',
    measurementId: 'G-HXRYTVRQM9',
  );
}
